### PR TITLE
add drag functionality

### PR DESCRIPTION
**Pull request by duck2**
I tried to keep this patch limited to drag.

The minimum requirement for drag was a data structure to wrap `Image` together with an update function and transformations. That is `Img`.

Now `drawCanvas()` iterates through all `Img`s and calls their draw function.

`mousedown` transforms and grabs an `Img`, `mouseup` lets it go, `mousemove` updates the canvas with new coordinates of `grab`.

See https://libduck2.github.io/pusula/ for a grasp. I think it will be easy to incorporate the envelope and other backgrounds.

### CODE REVIEW

**Comment by midorikocak** [comment]
Can you resolve conflicts?

**Comment by midorikocak** [comment]
thank you

**Comment by midorikocak** [comment]
1.does not detect the first click.
2. putting stamp takes time.
3. dragging does not work on mobile.

**Comment by duck2** [comment]
2 results from 1 I think. will look into it.
mobile drag will require [touch events](https://developer.mozilla.org/en/docs/Web/API/Touch_events).

**Comment by duck2** [comment]
this should have resolved the issues. mobile drag works now but stops working after zoom

**Comment by duck2** [comment]
works now. rejoice. any other problems?

**Pull request merged**
